# Configuration for mssql server

version: '3.9'

services:
  mailsystem:
    image: ${DOCKER_REGISTRY-}mailsystem
    build:
      context: .
      dockerfile: MailSystem/Dockerfile
    container_name: main_app
    environment:
      # configurate this variables
      DB_USERNAME: "sa"
      DB_HOST: "host.docker.internal"
      DB_PORT: "1433"
      DATABASE_NAME: "MailSystem"
      TRUSTED_CONNECTION: "True"
      ###
      # setup this variable in .env file
      DB_PASS: ${DB_PASSWORD}
      ###
    depends_on:
      - "sqlserver"
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    #--- If need connect for view db data
    ports:
      - "1433:1433"
    #---
    volumes:
      - ./../MailSystem_localdb/data:/var/opt/mssql/data
      - ./../MailSystem_localdb/log:/var/opt/mssql/log
      - ./../MailSystem_localdb/secrets:/var/opt/mssql/secrets
    environment:
      # setup this variable in .env file
      SA_PASSWORD: ${DB_PASSWORD}
      ###
      ACCEPT_EULA: "Y"